apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-shared-pv
  namespace: openwhisk
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/arrow/Desktop/openwhisk-test/python  # Replace with the path to your host folder
    type: DirectoryOrCreate
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-shared-pvc
  namespace: openwhisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: test-python-pod
  namespace: openwhisk
spec:
  containers:
  - name: my-container
    image: rggg1/python11action
    volumeMounts:
    - name: shared-volume
      mountPath: /something  # Mount the shared volume here
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: my-shared-pvc
