apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app

    spec:
      containers:
        - name: main-app
          image: main-app
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              protocol: TCP

