apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  namespace: 

spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app

    spec:
      containers:
        - name: main-app
          image: rggg1/main-app
          ports:
            - containerPort: 5000
              protocol: TCP

